projectType: extension
jdkTool: OPEN-JDK17
testJdkTool: OPEN-JDK8
additionalTestConfigs:
  jdk11:
    testJdkTool: OPEN-JDK11
  jdk17:
    testJdkTool: OPEN-JDK17
    mavenAdditionalArgs: -DdiscoverRuntimes.minMuleVersion=4.6.0
