projectType: extension
additionalTestConfigs:
  470:
    testJdkTool: TEMURIN-JDK8
    mavenAdditionalArgs: -Dtest=none -DfailIfNoTests=false -DruntimeProduct=MULE_EE -DruntimeVersion=4.7.0-rc3
#  jdk11:
#    testJdkTool: TEMURIN-JDK11
#    mavenAdditionalArgs: -Dtest=none -DfailIfNoTests=false -DruntimeVersion="4.4.0-20240215" -DadditionalRuntimeVersions="4.3.0-20231026"
#  jdk17:
#    testJdkTool: TEMURIN-JDK17
#    mavenAdditionalArgs: -Dtest=none -DfailIfNoTests=false -DruntimeVersion=4.6.0-rc3 -DruntimeProduct=MULE_EE