projectType: extension
additionalTestConfigs:
  jdk11:
    testJdkTool: TEMURIN-JDK11
    mavenAdditionalArgs: -DfailIfNoTests=false -DruntimeVersion="4.4.0-20240215" -DadditionalRuntimeVersions="4.3.0-20231026"
  jdk17:
    testJdkTool: TEMURIN-JDK17
    mavenAdditionalArgs: -DfailIfNoTests=false -DruntimeVersion=4.6.10 -DruntimeProduct=MULE_EE