projectType: extension
additionalTestConfigs:
  jdk11:
    testJdkTool: TEMURIN-JDK11
    mavenAdditionalArgs: -Dtest=none -DfailIfNoTests=false -DruntimeVersion="4.8.2" -DadditionalRuntimeVersions="4.3.0-20231026"
  jdk17:
    testJdkTool: TEMURIN-JDK17
    mavenAdditionalArgs: -Dtest=none -DfailIfNoTests=false -DruntimeVersion=4.7.4 -DruntimeProduct=MULE_EE