projectType: extension
jdkTool: OPEN-JDK17
testJdkTool: OPEN-JDK8
mavenAdditionalArgs: -DruntimeVersion=4.6.0-SNAPSHOT -DadditionalRuntimeVersions=4.6.0-SNAPSHOT -DruntimeProduct=MULE_EE
additionalTestConfigs:
  jdk11:
    testJdkTool: OPEN-JDK11
  jdk17:
    testJdkTool: OPEN-JDK17
    mavenAdditionalArgs: -DdiscoverRuntimes.minMuleVersion=4.6.0
